on: 
  push: 
    branches: [main]

jobs: 
  build: 
   name: 'build工作'
   runs-on: ubuntu-latest

   steps: 
     - name: 读取仓库内容
       uses: actions/checkout@v4

     - name: Deploy to Remote Server
       uses: appleboy/ssh-action@v1.0.3
       with: 
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_SEVER_KEY }}
        port: 22
        debug: true
        script: |
          echo "ssh 连接成功"

        
   
