on: 
  push: 
    branches: [main]

jobs: 
  build: 
   name: 'build工作'
   runs-on: ubuntu-latest

   steps: 
     - name: 读取仓库内容
       uses: actions/checkout@v4
      
     - name: 安装nodejs
       uses: actions/setup-node@v2
       with: 
        node-version: "22.x"  
      
     - name: 安装依赖和项目打包
       run: 
         npm install
         npm run build

     - name: copy dist file with scp
       uses: appleboy/scp-action@v0.0.1
       with: 
        host: ${{secrets.HOST}}
        username: ${{secrets.HOST}}
        password: ${{secrets.HOST}}
        port: 22
        source: 'build/'
        target: ${{secrets.TARGET}}

        
   
