on: 
  push: 
    branches: [main]

  workflow_dispatch: 


jobs: 
  build: 
   name: 'build工作'
   runs-on: ubuntu-latest

   steps: 
     - name: 读取仓库内容
       uses: actions/checkout@v4

     - name: 安装nodejs
       uses: actions/setup-node@v2.5.1
       with: 
        node-version: "22.x"
      
     - name: 安装依赖和项目打包
       run: 
         npm install
         npm run build
    
     - name: 部署
       uses: JamesIves/github-pages-deploy-action@v4
       with: 
        branch: gh-pages
        folder: build
   
